# Generated by Django 5.1.3 on 2024-11-26 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cpucooler',
            name='power',
        ),
    ]
