# Generated by Django 5.1.3 on 2024-11-26 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_cpucooler_power'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpu',
            name='boost_clock',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='core_clock',
            field=models.FloatField(),
        ),
    ]
