# Generated by Django 5.1.3 on 2024-11-26 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_cpu_boost_clock_alter_cpu_core_clock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpu',
            name='memory_clock',
            field=models.CharField(max_length=100),
        ),
    ]
