# Generated by Django 5.1.3 on 2024-11-29 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_case_price_cpu_price_cpucooler_price_gpu_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ram',
            name='operating_voltage',
            field=models.FloatField(),
        ),
    ]
