# Generated by Django 5.1.3 on 2024-11-29 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_ram_operating_voltage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='speed',
            field=models.CharField(max_length=100),
        ),
    ]
