# Generated by Django 5.1.3 on 2024-11-30 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_storage_speed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='price',
        ),
        migrations.RemoveField(
            model_name='cpu',
            name='price',
        ),
        migrations.RemoveField(
            model_name='cpucooler',
            name='price',
        ),
        migrations.RemoveField(
            model_name='gpu',
            name='price',
        ),
        migrations.RemoveField(
            model_name='mobo',
            name='price',
        ),
        migrations.RemoveField(
            model_name='psu',
            name='price',
        ),
        migrations.RemoveField(
            model_name='ram',
            name='price',
        ),
        migrations.RemoveField(
            model_name='storage',
            name='price',
        ),
    ]
