# Generated by Django 5.1.3 on 2024-11-30 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_remove_case_price_remove_cpu_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='cpu',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='cpucooler',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='gpu',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='mobo',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='psu',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='ram',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='storage',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
