# Generated by Django 5.1.3 on 2024-12-03 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_cartitem_order_orderitem'),
        ('products', '0011_case_shop_cpu_shop_cpucooler_shop_gpu_shop_mobo_shop_and_more'),
    ]

    operations = [
    ]
